name: Composio Meta Ads to Google Sheets Sync

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  sync-meta-ads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Execute Composio Workflow
        run: |
          response=$(curl -X POST "https://backend.composio.dev/api/v1/connectedAccounts/connectedaccount_f7dfff82-df8f-48e7-9505-e956ee376552/execute" \
            -H "Authorization: Bearer $COMPOSIO_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "input": {
                "trigger_type": "github_actions_scheduled"
              }
            }')
          echo "Resposta da API Composio: $response"
